import {
  createAsyncThunk, createSlice
  // , type PayloadAction
} from '@reduxjs/toolkit'
// Import { type RootState, type AppThunk } from '../../app/store'

// import { fetchDataGraph } from './dataGraphService'
import { type RootState } from '../../app/store'
import { fetchNodeProf, fetchTop } from './topsService'

export interface Top {
  profession: string
}

export interface Tops {professions: Top[] }

const initialState: Tops = { professions: [] }

/*
 * The function below is called a thunk and allows us to perform async logic. It
 * can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
 * will call the thunk with the `dispatch` function as the first argument. Async
 * code can then be executed and other actions can be dispatched. Thunks are
 * typically used to make async requests.
 */

export const getTops = createAsyncThunk(
  'tops/fetchTop',
  async () => {
    const response = await fetchTop()
    if (response.status === 200) {
      return response.data
    }
  }
)

export const getNodeProf = createAsyncThunk(
  'listJobs/fetchNodeProf',
  async (input: any) => {
    // eslint-disable-next-line no-debugger
    // const mock = { status: 200, professions: [{ profession: 'React Native Developer' }, { profession: 'Blockchain Developer' }], tips_to_learn: input + ' это один из наиболее востребованных навыков в разработке веб-приложений, поэтому его изучение обязательно будет полезным для вашей карьеры. Вот несколько советов и ресурсов, которые могут помочь вам изучить Typescript:\n\n1. Обязательно начинайте с основ, прежде чем переходить к более сложным темам.\n2. Практикуйтесь и делайте проекты, чтобы закрепить свои знания.\n3. Используйте онлайн-ресурсы, такие как курсы, видеоуроки и форумы, чтобы получить больше информации.\n\nТоп 5 бесплатных русскоязычных курсов:\n1. Курс от компании WebPurple: https://webpurple.netlify.app/\n2. Курс от LoftBlog: https://loftblog.ru/typescript-tutorial/\n3. Курс от компании Evil Martians: https://evilmartians.com/chronicles/typescript-1\n4. Курс от Learn.javascript.ru: https://learn.javascript.ru/typescript\n5. Курс от компании Otus: https://otus.ru/nest/post/421/\n\nТоп 4 бесплатных англоязычных курсов:\n1. Курс Learn TypeScript на сайте TypeScriptlang.org: https://www.typescriptlang.org/docs/handbook/intro.html\n2. Курс Advanced TypeScript на сайте Udemy: https://www.udemy.com/course/advanced-typescript/\n3. Курс на сайте Pluralsight: https://www.pluralsight.com/guides/typescript-getting-started\n4. Курс на сайте Scrimba: https://scrimba.com/learn/intrototypescript\n\nТоп 4 русскоязычных курсов:\n1. Курс от компании WebPurple: https://webpurple.netlify.app/\n2. Курс от LoftBlog: https://loftblog.ru/typescript-tutorial/\n3. Курс от компании Evil Martians: https://evilmartians.com/chronicles/typescript-1\n4. Курс от компании Otus: https://otus.ru/nest/post/421/\n\nТоп 3 англоязычных курсов:\n1. Курс на сайте Udemy: https://www.udemy.com/course/typescript-the-complete-developers-guide/\n2. Курс на сайте Pluralsight: https://www.pluralsight.com/courses/typescript-getting-started\n3. Курс на сайте Udacity: https://www.udacity.com/course/object-oriented-javascript--ud015\n\nСправочные материалы по этому навыку:\n1. Официальная документация TypeScript на сайте TypeScriptlang.org: https://www.typescriptlang.org/docs/\n2. Видеокурсы на сайте Egghead: https://egghead.io/courses/intro-to-typescript\n3. TypeScript Cheat Sheet: https://devhints.io/typescript' }
    // return mock
    // return { professions: [{ profession: input.distance }, { profession: '2' }] }
    const response = await fetchNodeProf(input)
    if (response.status === 200) {
      return response.data
    }
  }
)

export const TopsSlice = createSlice({
  name: 'tops',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
      /*
             * Redux Toolkit allows us to write "mutating" logic in reducers. It
             * doesn't actually mutate the state because it uses the Immer library,
             * which detects changes to a "draft state" and produces a brand new
             * immutable state based off those changes
             */

    },
    decrement: (state) => {
    }
  },

  /*
     * The `extraReducers` field lets the slice handle actions defined elsewhere,
     * including actions generated by createAsyncThunk or in other slices.
     */
  extraReducers: (builder) => {
    builder
      .addCase(getTops.pending, (state) => {
        return { professions: [] }
      })
      .addCase(getTops.fulfilled, (state, action) => {
        action.payload.professions = action.payload.professions.filter(el => el.profession !== 'NAN')
        return (action.payload) ? action.payload : state
      })
      .addCase(getTops.rejected, (state) => {
        return { professions: [] }
      })
  }
})
export const ListJobsSlice = createSlice({
  name: 'listJobs',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
      /*
             * Redux Toolkit allows us to write "mutating" logic in reducers. It
             * doesn't actually mutate the state because it uses the Immer library,
             * which detects changes to a "draft state" and produces a brand new
             * immutable state based off those changes
             */

    },
    decrement: (state) => {
    }
  },

  /*
     * The `extraReducers` field lets the slice handle actions defined elsewhere,
     * including actions generated by createAsyncThunk or in other slices.
     */
  extraReducers: (builder) => {
    builder
      .addCase(getNodeProf.pending, (state) => {
        return { professions: [] }
      })
      .addCase(getNodeProf.fulfilled, (state, action) => {
        action.payload.professions = action.payload.professions.filter(el => el.profession !== 'NAN')
        return (action.payload) ? action.payload : state
      })
      .addCase(getNodeProf.rejected, (state) => {
        return { professions: [] }
      })
  }
})
// Export const { incrementByAmount } = gradeSlice.actions

/*
 * The function below is called a selector and allows us to select a value from
 * the state. Selectors can also be defined inline where they're used instead of
 * in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
 */
export const selectDataTops = (state: RootState): Tops => state.top
export const selectListJobs = (state: RootState): Tops => state.listJob
//
// // We can also write thunks by hand, which may contain both sync and async logic.
// // Here's an example of conditionally dispatching actions based on current state.
// Export const incrementIfOdd =
//     (amount: number): AppThunk =>
//       (dispatch, getState) => {
//         Const currentValue = selectCount(getState())
//         If (currentValue % 2 === 1) {
//           Dispatch(incrementByAmount(amount))
//         }
//       }
