name: deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: sample:dev
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
            # TODO: add env vars as secrets on GitHub
        with:
              host: ${{ secrets.VPS_SSH_HOST }}
              username: ${{ secrets.VPS_SSH_USERNAME }}
              key: ${{ secrets.VPS_SSH_SECRET }}
              port: ${{ secrets.VPS_SSH_PORT }}
              script: |
                echo "Pull new image"
                sudo docker build -t sample:dev .  pull
                echo "Restart the container"
                docker restart $(docker ps -a -q --filter ancestor=sample:dev --format="{{.ID}}")
