name: CD

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:      
  deploy:
        runs-on: ubuntu-latest   

        steps:
          - name: Deploy to VPS
            uses: appleboy/ssh-action@master
            # TODO: add env vars as secrets on GitHub
            with:
              # VPS IP
              host: ${{ secrets.VPS_SSH_HOST }}
              # VPS username
              username: ${{ secrets.VPS_SSH_USERNAME }}
              # SSH key (copy it from your local machine)
              key: ${{ secrets.VPS_SSH_SECRET }}
              # SSH port
              port: ${{ secrets.VPS_SSH_PORT }}
              script: |
                echo "Pull new image"
                sudo docker build -t sample:dev .  pull
                echo "Restart the container"
                docker restart $(docker ps -a -q --filter ancestor=sample:dev --format="{{.ID}}")
